// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gincdolfdjxbpnpyqrzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpbmNkb2xmZGp4YnBucHlxcnp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjY4MTcsImV4cCI6MjA2MDkwMjgxN30.PqSSOSnfhUurkc34ffFqlRoXWnKb2cR-_PcGjOy8H2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);